# Generated by Django 5.2.6 on 2025-09-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo del Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_propietario', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MANANA', max_length=6, verbose_name='Turno de Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='guardia',
            name='created',
        ),
    ]
