# Generated by Django 5.2.6 on 2025-09-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_administrador_propietario_secretaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('capacidad_maxima', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Hora')),
                ('reglamento', models.TextField(verbose_name='Reglamento del Área')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Reserva')),
                ('area_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_area', to='gestion.areasocial')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_propietario', to='gestion.propietario')),
            ],
        ),
    ]
