# Generated by Django 5.2.6 on 2025-09-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedad', '0001_initial'),
        ('gestion', '0003_areasocial_reservaarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Deuda')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('pagada', models.BooleanField(default=False, verbose_name='¿Está pagada?')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('unidad_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_unidad', to='Propiedad.unidadhabitacional')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Queja')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PROCESO', 'En Proceso'), ('CERRADA', 'Cerrada'), ('RESUELTA', 'Resuelta')], default='ABIERTA', max_length=10, verbose_name='Estado de la Queja')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas_reportadas', to='gestion.propietario')),
                ('unidad_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas_unidad', to='Propiedad.unidadhabitacional')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(verbose_name='Fecha y Hora de Entrada')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Salida')),
                ('nombre_visitante', models.CharField(max_length=100, verbose_name='Nombre del Visitante')),
                ('ci_visitante', models.CharField(max_length=20, verbose_name='CI del Visitante')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, verbose_name='Placa del Vehículo')),
                ('guardia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to='gestion.guardia')),
                ('unidad_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_unidad', to='Propiedad.unidadhabitacional')),
            ],
        ),
    ]
