# Generated by Django 5.2.6 on 2025-09-29 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_Cond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='datos_secretaria', serialize=False, to='user_Cond.perfiluser')),
                ('turno', models.CharField(choices=[('MAÑANA', 'mañana'), ('TARDE', 'tarde'), ('NOCHE', 'noche')], default='MAÑANA', max_length=20)),
                ('velocidad_teclado', models.IntegerField(default=40)),
            ],
        ),
    ]
