# Generated by Django 5.2.6 on 2025-09-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion_Cond', '0001_initial'),
        ('Propietarios_Cond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDespensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechade_pago', models.DateField()),
                ('monto', models.FloatField()),
                ('is_principal', models.BooleanField(default=True)),
                ('UnidadH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_despensa', to='Propietarios_Cond.unidadhabitacional')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_despensa', to='Propietarios_Cond.propietario')),
            ],
        ),
    ]
