# Generated by Django 5.2.6 on 2025-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion_Cond', '0002_pagodespensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodespensa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
