# Generated by Django 5.2.6 on 2025-09-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0002_administrador_propietario_secretaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentes', models.TextField(verbose_name='Residentes')),
                ('manzano', models.CharField(max_length=10, verbose_name='Manzano')),
                ('lote', models.CharField(max_length=10, verbose_name='Lote')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_habitacionales', to='gestion.propietario')),
            ],
        ),
    ]
