# Generated by Django 5.2.6 on 2025-09-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_Cond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='datos_propietario', serialize=False, to='user_Cond.perfiluser')),
                ('is_activo', models.BooleanField(default=True)),
                ('codigo_propietario', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('piso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobilitad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('imangen_url', models.URLField(blank=True, null=True)),
                ('propietarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilidades', to='Propietarios_Cond.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiene'), ('EN_PROCESO', 'proceso'), ('RESUELTO', 'resuelto'), ('CERRADO', 'cerrado')], default='EN_PROCESO', max_length=20)),
                ('propietarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='Propietarios_Cond.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAreaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('is_principal', models.BooleanField(default=False)),
                ('AreaSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='Propietarios_Cond.areasocial')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posesiones', to='Propietarios_Cond.propietario')),
                ('unidad_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='Propietarios_Cond.unidadhabitacional')),
            ],
        ),
    ]
