# Generated by Django 5.2.6 on 2025-10-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propietarios_Cond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroareasocial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_area_social', to='Propietarios_Cond.propietario'),
        ),
    ]
