# Generated by Django 5.2.6 on 2025-09-29 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Propietarios_Cond', '0001_initial'),
        ('user_Cond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='datos_guardia', serialize=False, to='user_Cond.perfiluser')),
                ('turno', models.CharField(choices=[('MAÑANA', 'mañana'), ('TARDE', 'tarde'), ('NOCHE', 'noche')], default='MAÑANA', max_length=20)),
                ('is_activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('informacion_adicional', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('UnidadHabitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propietarios_Cond.unidadhabitacional')),
            ],
        ),
    ]
